project_id = "lhaqqqatdztuijgdfdcf"

[functions.announcements-feed-format]
verify_jwt = false

[functions.translate-urdu]
verify_jwt = false

[functions.create-donation-option-stripe]
verify_jwt = true

[functions.process-recurring-notifications]
verify_jwt = true
